/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;

import static org.junit.Assert.*;
import org.junit.Before;
import java.io.PrintStream;
import java.io.ByteArrayOutputStream;
import java.util.List;

public class LibraryTest {

  // https://stackoverflow.com/questions/1119385/junit-test-for-system-out-println
  private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();

  @Before
  public void setUpStreams() {
    System.setOut(new PrintStream(outContent));
  }

  @Test public void testRoll() {
    int[] rolls = Library.roll(4);
    assertTrue("Times dice rolled:", rolls.length == 4);
  }

  @Test public void testContainsDuplicates() {
    int[] inputArr = new int[]{1,2,2,4};
    assertTrue("There are duplicates", Library.containsDuplicates(inputArr));
  }

  @Test public void testDoesNotContainDuplicates(){
    int[] inputArr = new int[]{1,2,3,4};
    assertFalse("There are no duplicates:", Library.containsDuplicates(inputArr));
  }

  @Test public void testCalculateAvg() {
    int[] inputArr = new int[]{1,2,3,4};
    double avg = Library.calculateAvg(inputArr);
    assertTrue("Avg is:", avg == 2.5);
  }

  @Test public void testArrayAvgValue() {
    int[][] weeklyMonthTemperatures = {
        {66, 64, 58, 65, 71, 57, 60},
        {57, 65, 65, 70, 72, 65, 51},
        {55, 54, 60, 53, 59, 57, 61},
        {65, 56, 55, 52, 55, 62, 57}
    };
    String test = Arrays.toString(weeklyMonthTemperatures[2]);
    String result = Library.arrayAvgValue(weeklyMonthTemperatures);
    assertEquals("Test should equal result:", test, result);
  }

  @Test public void testAnalyzingWeatherData(){
    int[][] weeklyMonthTemperatures = {
        {66, 64, 58, 65, 71, 57, 60},
        {57, 65, 65, 70, 72, 65, 51},
        {55, 54, 60, 53, 59, 57, 61},
        {65, 56, 55, 52, 55, 62, 57}
    };
    Library.analyzeWeatherdata(weeklyMonthTemperatures);
    assertEquals("High: 72\n" + "Low: 51\n" + "Never saw temperature: 63\n" + "Never saw temperature: 67\n" + "Never " +
        "saw temperature: 68\n" + "Never saw temperature: 69\n", outContent.toString());
  }

  @Test public void testTally(){
    List<String> votes = new ArrayList<>();
    votes.add("Bush");
    votes.add("Bush");
    votes.add("Bush");
    votes.add("Shrub");
    votes.add("Hedge");
    votes.add("Shrub");
    votes.add("Bush");
    votes.add("Hedge");
    votes.add("Bush");

    String winner = Library.tally(votes);
    System.out.println(winner + " received the most votes!");
    assertEquals("Winner is: ", "Bush", Library.tally(votes));
  }

}
