/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
  @Test public void testRoll() {
    int[] rolls = Library.roll(4);
    assertTrue("Times dice rolled:", rolls.length == 4);
  }

  @Test public void testContainsDuplicates() {
    int[] inputArr = new int[]{1,2,2,4};
    assertTrue("There are duplicates", Library.containsDuplicates(inputArr));
  }

  @Test public void testDoesNotContainDuplicates(){
    int[] inputArr = new int[]{1,2,3,4};
    assertFalse("There are no duplicates:", Library.containsDuplicates(inputArr));
  }

  @Test public void testCalculateAvg() {
    int[] inputArr = new int[]{1,2,3,4};
    double avg = Library.calculateAvg(inputArr);
    assertTrue("Avg is:", avg == 2.5);
  }

  @Test public void testArrayAvgValue() {
    int[][] weeklyMonthTemperatures = {
        {66, 64, 58, 65, 71, 57, 60},
        {57, 65, 65, 70, 72, 65, 51},
        {55, 54, 60, 53, 59, 57, 61},
        {65, 56, 55, 52, 55, 62, 57}
    };
    String test = Arrays.toString(weeklyMonthTemperatures[2]);
    String result = Library.arrayAvgValue(weeklyMonthTemperatures);
    assertEquals(test, result);
  }
}
