/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Arrays;

public class Library {

  public static int[] roll(int n) {
    int[] rolls = new int[n];
    for(int i = 0; i < n; i++){
      rolls[i] = (int)((Math.random() * 6) + 1);
    }
    return rolls;
  }

  public static boolean containsDuplicates(int[] arr){
    for(int j = 0; j < arr.length; j++){
      for(int k = 1; k < arr.length; k++){
        if(arr[j] == arr[k] && j != k) return true;
      }
    }
    return false;
  }

  public static double calculateAvg(int[] arr){
    double sum = 0;
    for(int i = 0; i < arr.length; i++){
      sum += arr[i];
    }
    return sum/arr.length;
  }

  public static String arrayAvgValue(int[][] arr){
    ArrayList<Integer> averages = new ArrayList<>();
    int lowestAvg = Integer.MAX_VALUE;
    int lowestAvgIndex = 0;
    int avg = 0;
    for(int i = 0; i < arr.length; i++){
      int sum = 0;
      for(int j = 0; j < arr[i].length; j++){
        sum += arr[i][j];
        avg = sum/arr[i].length;
      }
      averages.add(avg);
    }

    for(int k = 0; k < averages.size(); k++){
      if(averages.get(k) < lowestAvg){
        lowestAvg = averages.get(k);
        lowestAvgIndex = k;
      }
    }
    return Arrays.toString(arr[lowestAvgIndex]);
  }
}

